### PR TITLE
Mask Unnecesssary services

### PR DESCRIPTION
**Pull request by unman**
Deals with QubesOS/qubes-issues#5206 in new templates.

### CODE REVIEW

**Comment by adrelanos** [comment]
I don't think `systemctl mask` is the correct tool here. systemd drop-in config snippets are better. This is already implemented for some services btw.

**Comment by unman** [comment]
> I don't think `systemctl mask` is the correct tool here. systemd drop-in config snippets are better. This is already implemented for some services btw.

mask is the canonical way of stopping services from being started and is what we recommend for new services installed in templates in Debian. It's the obvious tool

**Comment by adrelanos** [comment]
systemctl mask is for local system administrator. Not for linux distribution maintainers.

Using systemctl mask in Qubes Builder results in inconsistent behavior: new templates will have these systemd services masked, while users who upgrade their templates, will not have this change.

Using systemctl mask from packaging maintainer scripts would be even worse. Then later on,  packaging maintainer scripts could not distinguish if systemctl mask was used by the local system administrator (needlessly again) or by packaging maintainer scripts. Therefore umask by packaging maintainer scripts could violate user decisions.

Doing this in the Qubes Builder is also somewhat intransparent buried somewhere. Why this is so is not easily knowable form within the VM. For example if one is wondering why cron isn't running, then sudo systemctl status cron will tell that there is a drop-in file /lib/systemd/system/cron.service.d/30_qubes.conf. Such drop-in files can even have comments explaining why they do what they are doing.

And a local system administrator can add drop-in files on their own on top to undo that configuration without interfering with the package that shipped the original drop-in.

There is already a ton of drop-in files here:
https://github.com/QubesOS/qubes-core-agent-linux/tree/master/vm-systemd

I don't think it's a good idea to break with that tradition now.

**Comment by marmarek** [comment]
> mask is the canonical way of stopping services from being started

As Patrick already said, it is not a good tool for that. If nothing else, then because of difference between updated and reinstalled template.
If possible (unit can be enabled/disabled), use [preset file](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/vm-systemd/75-qubes-vm.preset). Otherwise, use drop-in files.

**Review by marmarek — CHANGES_REQUESTED** [review]
As said in the comment - mask is not a good way to do that.

**Pull request closed without merging**
