### PR TITLE
Fix DNS resolution in bionic templates

### LINKED ISSUE #4828: [Fixed] DNS resolution does not work when using ubuntu bionic as sys-net template
### Qubes OS version:
R4.0

### Affected component(s):
Ubuntu bionic / sys-net

---

### Steps to reproduce the behavior:
1.) Build ubuntu bionic template
2.) Set sys-net to use bionic as template
3.) Start sys-net

### Expected behavior:
DNS resolution should be setup properly to allow all connected VMs (typically sys-firewall only) to resolve DNS lookups.

### Actual behavior:
Whilst sys-net can perform lookups - absolutely no connected VMs can.

### General notes:

---

### Resolution:

I have already determined the problem and a possible resolution but I'm on not sure where this is built in the first place to submit a PR?

1.) After building the ubuntu template - run terminal on it
2.) Run "systemctl disable systemd-resolved"
3.) In the file /etc/NetworkManager/NetworkManager.conf below the "[main]" heading - add "dns=default"
4.) Stop ubuntu template
5.) Reboot Qubes completely to ensure the template changes are pushed out to sys-net and bang - working DNS for all.

If anyone can guide me on where I can PR this I'm more than happy to. Just wanted to document the resolution to this since it's a really simple fix when you know how! :)

### PR DESCRIPTION
**Pull request by unman**
Allows bionic to be used as sys-net with correct DNS
Closes QubesOS/qubes-issues#4828
Thanks to @cawilliamson for identifying problem and providing solution

### CODE REVIEW

**Review by marmarek — DISMISSED** [review]

**Comment by marmarek** [comment]
Hmm, actually, wouldn't it be better to handle NetworkManager.conf in core-agent-linux, where we already do it anyway? https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/qubes-fix-nm-conf.sh

**Comment by unman** [comment]
@marmarek I've been testing and adding` dns=default` works fine in every template: how would you feel to adding that in every case, unless there's already a dns entry, presumably because user has chosen to set one?

**Comment by marmarek** [comment]
That should be fine. But still, the right place to do it is in https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/qubes-fix-nm-conf.sh

**Comment by unman** [comment]
On Wed, Jun 26, 2019 at 08:48:08AM -0700, Marek Marczykowski-G??recki wrote:
> That should be fine. But still, the right place to do it is in https://github.com/QubesOS/qubes-core-agent-linux/blob/master/network/qubes-fix-nm-conf.sh
> 

Yes

**Pull request closed without merging**
